#include "hcf/trace/warning_macros.h"

#define TRACEPOINT_CREATE_PROBES

/*
 * Start from this point onwards to ignore all the warnings generated by LTTnG
 * library (sigh!) due to the usage of -Wall and -Wextra compiler flags.
 * We'll restore the default behavior as soon LTTnG library header files are not used anymore!
 */
TURN_OFF_WARNINGS_INTO_LTTNG_LIBRARY_BEGIN

#include "com_ericsson_test_common.h"
#include "com_ericsson_test_class1.h"

/*
 * All the LTTnG library files have been included now (hurrah!), we can use our compiler flags!
 */
TURN_OFF_WARNINGS_INTO_LTTNG_LIBRARY_END
